[phases.setup]
nixPkgs = ["php83", "nodejs_20", "php83Packages.composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader", "npm install"]

[phases.build]
cmds = ["npm run build", "chmod -R 775 storage bootstrap/cache"]

[start]
cmd = "php artisan config:cache && php artisan route:cache && php artisan migrate --force && php artisan serve --host 0.0.0.0 --port $PORT"